version: '3.7'

services:
  pets:
    image: tensorflow/serving
    ports:
      - "8501:8501"
    container_name: pets
    environment:
      - MODEL_NAME=pets
    volumes:
      - ./pets:/models/pets/1

  postgres_db:
    image: postgres
    container_name: postgres_db
    environment:
      - POSTGRES_DB=project
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=project
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
